import React from 'react'

export default ({ width, height }) => (
  <svg
    version="1.1"
    width={width}
    height={height}
    viewBox="-0.5 -0.5 303 304"
    preserveAspectRatio="xMidYMid meet"
  >
    <defs />
    <g>
      <ellipse
        cx="150"
        cy="150"
        rx="150"
        ry="150"
        fill="#000000"
        stroke="none"
        transform="translate(2,3)"
        opacity="0.25"
      />
      <ellipse
        cx="150"
        cy="150"
        rx="150"
        ry="150"
        fill="#ccac76"
        stroke="none"
        pointerEvents="none"
      />
      <rect
        x="37.5"
        y="72.5"
        width="225"
        height="155"
        rx="23.25"
        ry="23.25"
        fill="#000000"
        stroke="none"
        transform="translate(2,3)"
        opacity="0.25"
      />
      <rect
        x="37.5"
        y="72.5"
        width="225"
        height="155"
        rx="23.25"
        ry="23.25"
        fill="#3f2c2b"
        stroke="none"
        pointerEvents="none"
      />
      <rect
        x="43"
        y="78"
        width="214"
        height="143"
        rx="21.45"
        ry="21.45"
        fill="#b87333"
        stroke="none"
        pointerEvents="none"
      />
      <rect
        x="140"
        y="120"
        width="126"
        height="60"
        rx="9"
        ry="9"
        fill="#000000"
        stroke="none"
        transform="translate(2,3)"
        opacity="0.25"
      />
      <rect
        x="140"
        y="120"
        width="126"
        height="60"
        rx="9"
        ry="9"
        fill="#e3c171"
        stroke="none"
        pointerEvents="none"
      />
      <rect
        x="138"
        y="120"
        width="120"
        height="60"
        rx="9"
        ry="9"
        fill="#743922"
        stroke="none"
        pointerEvents="none"
      />
      <ellipse
        cx="170"
        cy="150"
        rx="20"
        ry="20"
        fill="#000000"
        stroke="none"
        transform="translate(2,3)"
        opacity="0.25"
      />
      <ellipse
        cx="170"
        cy="150"
        rx="20"
        ry="20"
        fill="#dcd8d2"
        stroke="none"
        pointerEvents="none"
      />
    </g>
  </svg>
)
